### PR TITLE
Mention Android app bundles in doc

### PR DESCRIPTION
**Pull request by LouisCAD**
BTW, you can't publish a new app as an apk, only Android app bundles are accepted on the Play Store now.

### CODE REVIEW

**Comment by amakeev** [comment]
@LouisCAD I believe AABs are not exactly a packaging format, but rather a publishing format (as per [the official doc](https://developer.android.com/guide/app-bundle/faq)). Is that right?

**Comment by LouisCAD** [comment]
Are there Amper specific distinctions and definitions to those two terms?

To me, developing Android apps since 2014, an Android app can be packaged as both an android package (apk) and an android app bundle (aab), and both can be published, though the Play Store now accepts only aab for new apps.

For Firebase App Distribution, both are supported for example.

**Comment by amakeev** [comment]
@LouisCAD I believe it's both, as the android documentation also describes AAB as a publishing format. In Amper we are designing packaging and publishing as related but separate things, as they take part in different workflows (e.g. installing on a device vs publishing in an App Store).

Would you like to mention AABs in the Publishing section instead?

**Comment by amakeev** [comment]
@LouisCAD I've updated the document to mention AABs in publishing. Here is the [commit](https://github.com/JetBrains/amper/commit/183c7a4b77215e88e8cea593349412a025e6a23a).
Thanks for the contribution!

**Pull request closed without merging**
